DROP TABLE IF EXISTS permissao CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;
DROP TABLE IF EXISTS solicitacao_amizade CASCADE;
DROP TABLE IF EXISTS post CASCADE;
DROP TABLE IF EXISTS amigo CASCADE;

CREATE TABLE usuario (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nome VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	apelido VARCHAR(50),
	data_nascimento DATE NOT NULL,
	senha VARCHAR(128) NOT NULL,
	url_imagem VARCHAR(512),
	ativo BOOLEAN NOT NULL
);
ALTER TABLE usuario ADD CONSTRAINT pk_usuario PRIMARY KEY (id);
ALTER TABLE usuario ADD CONSTRAINT uk_usuario_email UNIQUE (email);

CREATE TABLE permissao (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nome VARCHAR(100) NOT NULL,
	usuario_id BIGINT NOT NULL
);
ALTER TABLE permissao ADD CONSTRAINT pk_permissao PRIMARY KEY (id);
ALTER TABLE permissao ADD CONSTRAINT uk_permissao UNIQUE (nome, usuario_id);
ALTER TABLE permissao ADD CONSTRAINT fk_permissao_usuario FOREIGN KEY (usuario_id) REFERENCES usuario;

CREATE TABLE solicitacao_amizade (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  	usuario_id BIGINT NOT NULL,
  	usuario_solicitou_id BIGINT NOT NULL
);
ALTER TABLE solicitacao_amizade ADD CONSTRAINT pk_solicitacao_amizade PRIMARY KEY (id);
ALTER TABLE solicitacao_amizade ADD CONSTRAINT fk_usuario_id FOREIGN KEY (usuario_id) REFERENCES usuario;
ALTER TABLE solicitacao_amizade ADD CONSTRAINT fk_usuario_solicitou FOREIGN KEY (usuario_solicitou_id) REFERENCES usuario;

CREATE TABLE post (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   	id_usuario BIGINT NOT NULL,
   	url_postagem VARCHAR,
   	data_postagem DATE NOT NULL
);
ALTER TABLE post ADD CONSTRAINT pk_post PRIMARY KEY (id);
ALTER TABLE post ADD CONSTRAINT fk_id_usuario FOREIGN KEY (id_usuario) REFERENCES usuario;

CREATE TABLE amigo(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_usuario BIGINT NOT NULL,
    id_usuario_amigo BIGINT NOT NULL
);
ALTER TABLE amigo ADD CONSTRAINT pk_amigo PRIMARY KEY (id);
ALTER TABLE amigo ADD CONSTRAINT fk_id_usuario FOREIGN KEY (id_usuario) REFERENCES usuario;
ALTER TABLE amigo ADD CONSTRAINT fk_id_usuario_amigo FOREIGN KEY (id_usuario_amigo) REFERENCES usuario;

